$theme: 103
$layout: dagre


# - data flow: greatfet one ---------------------------------------------------
diagram_0: Data Flow: GreatFET One
diagram_0: {
    $include: greatfet.d2
}

# - data flow: luna -----------------------------------------------------------
diagram_1: Data Flow: Luna
diagram_1: {
    $include: luna.d2
}



# - Facedancer.git ------------------------------------------------------------

#facedancer: facedancer.git


# - libgreat.git --------------------------------------------------------------

#libgreat: libgreat.git

# libgreat/host/pygreat
#libgreat.pygreat: libgreat/host/pygreat/


# - libgreat-rs.git -----------------------------------------------------------

#libgreat-rs: libgreat-rs.git


# - luna.git ------------------------------------------------------------------

#luna: luna.git

# examples
#luna.examples: luna/examples/
# luna.examples.blinky: luna/examples/blinky/
# luna.examples.soc_bios: luna/examples/soc/bios/
# luna.examples.soc_hello: luna/examples/soc/hello/
# luna.examples.usb: luna/examples/usb/
# luna.examples.usb.loopback: luna/examples/usb/loopback.py
# luna.examples.usb.simple_device: luna/examples/usb/simple_device.py
# luna.examples.usb.stress_test_device: luna/examples/usb/stress_test_device.py

# gateware
#luna.gateware: luna/gateware/
# luna.gateware.applets: luna/gateware/applets/
# luna.gateware.applets.analyzer: luna/gateware/applets/analyzer.py
# luna.gateware.applets.dc_flash: luna/gateware/applets/dc_flash.py
# luna.gateware.architecture_car: luna/gateware/architecture/car.py
# luna.gateware.debug: luna/gateware/debug/
# luna.gateware.interface: luna/gateware/interface/
# luna.gateware.memory.py: luna/gateware/memory.py
# luna.gateware.platform: luna/gateware/platform/
# luna.gateware.soc: luna/gateware/soc/
# luna.gateware.stream: luna/gateware/stream/
# luna.gateware.test: luna/gateware/test/
# luna.gateware.usb: luna/gateware/usb/


# firmware
#luna.firmware: luna/firmware/
