#[target.riscv32i-unknown-none-elf]
#rustflags = [
#  "-C", "link-arg=-Tmemory.x",
#  "-C", "link-arg=-Tlink.x",
#]

#[unstable]
#build-std = ["core", "compiler_builtins"]

[build]
target = "riscv32i-unknown-none-elf"
