[target.riscv32i-unknown-none-elf]
runner = ".cargo/flash.sh"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  # generate a linker map
  # "-C", "link-args=-Map=/tmp/firmware.map",
]

[target.riscv32imac-unknown-none-elf]
runner = ".cargo/flash.sh"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

[target.riscv32imc-unknown-none-elf]
runner = ".cargo/flash.sh"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]


[build]
target = "riscv32i-unknown-none-elf"
#target = "riscv32imac-unknown-none-elf"
#target = "riscv32imc-unknown-none-elf"
