# - Luna Examples -------------------------------------------------------------

luna_git.examples_soc: examples/soc/
luna_git.examples_soc.text: |c
    bios/
    hello/
|
#luna_git.examples_soc: {
#    near: luna_git.firmware
#}
