# - Luna SoC ------------------------------------------------------------------

luna_git.gateware_soc: luna/gateware/soc/
luna_git.gateware_soc.lunasoc: luna/gateware/soc/lunasoc.py
luna_git.gateware_soc.lunasoc: {
    cpu: minerva
    bus_arbiter: bus arbiter
    bus_decoder: bus decoder
    intc: interrupt controller

    gpio
    hyperram
    jtag
    pmod: pmod0, pmod1
    spiflash
    sram
    timer
    uart
    usb: usb0, usb1, usb2

    cpu -- jtag
    cpu -- bus_arbiter
    bus_arbiter -- bus_decoder
    bus_decoder -- intc
    intc -- cpu
    uart -- intc
    timer -- intc

    bus_decoder -- gpio
    bus_decoder -- hyperram
    bus_decoder -- spiflash
    bus_decoder -- sram
    bus_decoder -- timer
    bus_decoder -- uart
    bus_decoder -- usb

    gpio -- pmod
}

luna_git.gateware_soc.cgen: luna/gateware/soc/cgen.py
luna_git.gateware_soc.cgen.text: |c
    resources.h
    soc.ld
|

luna_git.gateware_soc.svdgen: luna/gateware/soc/svdgen.py
luna_git.gateware_soc.svdgen.text: |c
    lunasoc.svd
|


# styles

luna_git.gateware_soc.lunasoc.cpu.style: { fill: lightblue }
luna_git.gateware_soc.lunasoc.bus_arbiter.style: { fill: lightgreen }
luna_git.gateware_soc.lunasoc.bus_decoder.style: { fill: lightgreen }
luna_git.gateware_soc.lunasoc.intc.style: { fill: lightgreen }

luna_git.gateware_soc.lunasoc.gpio.style.fill: orange
luna_git.gateware_soc.lunasoc.hyperram.style.fill: orange
luna_git.gateware_soc.lunasoc.spiflash.style.fill: orange
luna_git.gateware_soc.lunasoc.sram.style.fill: orange
luna_git.gateware_soc.lunasoc.timer.style.fill: orange
luna_git.gateware_soc.lunasoc.uart.style.fill: orange
luna_git.gateware_soc.lunasoc.usb.style.fill: orange


# internal relationships

luna_git.gateware_soc.lunasoc -> luna_git.gateware_soc.cgen
luna_git.gateware_soc.lunasoc -> luna_git.gateware_soc.svdgen


# external relationships

#luna_git.gateware_soc.cgen -- luna_git.examples_soc
#luna_git.gateware_soc.svdgen -- luna_git.firmware.lunasoc-pac: svd2rust
