# - key -----------------------------------------------------------------------

# key: {
#      port: {
#          fill: lightblue
#      }
#      create: {
#          fill: red
#      }
#      re-use: {
#          fill: lightgreen
#      }
# }

# - data flow: greatfet one ---------------------------------------------------

diagram_0: Data Flow: GreatFET One
diagram_0: {
    facedancer_git: facedancer.git
    facedancer_git.backends_greatdancer: facedancer/backends/greatdancer.py

    libgreat_git: libgreat.git
    libgreat_git.host_pygreat: host/pygreat/
    libgreat_git.firmware: firmware/
    libgreat_git.firmware.drivers: firmware/drivers/
    libgreat_git.firmware.platform_drivers: firmware/platform/lpc43xx/drivers/

    greatfet_git: greatfet.git
    greatfet_git.firmware: firmware/greatfet_usb/
    greatfet_git.host_greatfet: host/greatfet/greatfet.py

    azalea_git: @greatfet-hardware/azalea.git
    azalea_git.lpc4330: U1 LPC4330FBD144
    azalea_git.lpc4330.usb0: usb0
    azalea_git.lpc4330.usb1: usb1
    azalea_git.lpc4330.etc: "..."
    azalea_git.w25q16dv: U2 W25Q16DV
    #azalea_git.j1: J1
    #azalea_git.j2: J2
    #azalea_git.j3: J3 USB0
    #azalea_git.j4: J4 USB1
    #azalea_git.j5: J5 JTAG
    #azalea_git.j7: BONUS_ROW

    # connections
    facedancer_git <-> greatfet_git.host_greatfet: {
        label: python
        style: {
            font-size: 24
            stroke-width: 5
            stroke: blue
        }
    }

    greatfet_git.host_greatfet <-> libgreat_git.host_pygreat: {
        label: python
        style: {
            font-size: 24
            stroke-width: 5
            stroke: blue
        }
    }

    libgreat_git.host_pygreat <-> libgreat_git.firmware: {
        label: usb
        style: {
            font-size: 24
            stroke-width: 5
            stroke: green
        }
    }

    libgreat_git.firmware.platform_drivers <-> azalea_git.lpc4330: {
        label: C
        style: {
            font-size: 24
            stroke-width: 5
            stroke: red
        }
    }

    libgreat_git.firmware <-> greatfet_git.firmware: {
        label: C
        style: {
            font-size: 24
            stroke-width: 5
            stroke: red
        }
    }

    greatfet_git.firmware <-> azalea_git: {
        label: C
        style: {
            font-size: 24
            stroke-width: 5
            stroke: red
        }
    }
}


# - data flow: luna -----------------------------------------------------------

diagram_1: Data Flow: Luna
diagram_1: {
    facedancer_git: facedancer.git
    facedancer_git.backends_moondancer: facedancer/backends/moondancer.py
    facedancer_git.backends_moondancer_img: {
        label: ""
        shape: image
        icon: https://static.wikia.nocookie.net/mlp/images/5/51/Moon_Dancer_ID_S5E12.png
    }

    greatfet_git: luna.git/host/
    greatfet_git.host_greatfet: host/luna/luna.py
    greatfet_git.host_greatfet_txt: |
        Basically greatfet.git/host/greatfet/ minus the bits we don\'t need?

    | {
        near: diagram_1.greatfet_git.host_greatfet
    }

    libgreat_git: libgreat.git
    libgreat_git.host_pygreat: host/pygreat/
    libgreat_git.host_pygreat_txt: |
        Can we use the GreatFET Communications Protocol implementation as-is?
    | {
        near: diagram_1.greatfet_git.host_greatfet
    }

    libgreat-rs_git: libgreat-rs.git
    libgreat-rs_git.firmware: firmware/
    libgreat-rs_git.firmware.drivers: firmware/drivers/
    libgreat-rs_git.firmware.platform_drivers: firmware/platform/soc/drivers/

    luna_git: luna.git

    luna_git.firmware: firmware/
    luna_git.firmware.soc: luna/firmware/soc/

    luna_git.gateware: luna/gateware/
    luna_git.gateware.soc: luna/gateware/soc/
    #luna_git.gateware.usb: luna/gateware/usb/

    luna_git.hardware: hardware/
    luna_git.hardware.ecp5: LFE5U-12F-6BG256C
    luna_git.hardware.usb-j1: U11 USB3343
    luna_git.hardware.usb-j2: U8 USB3343
    luna_git.hardware.usb-j3: U9 USB3343
    luna_git.hardware.etc: "..."
    #luna_git.hardware.hyperram: W956A8MBYA6I
    #luna_git.hardware.spiflash: W25Q32JVSSIQ
    #luna_git.hardware.atsamd: ATSAMD11D14A-MUT

    # connections
    facedancer_git <-> greatfet_git.host_greatfet: {
        label: python
        style: {
            font-size: 24
            stroke-width: 5
            stroke: blue
        }
    }

    greatfet_git.host_greatfet <-> libgreat_git.host_pygreat: {
        label: python
        style: {
            font-size: 24
            stroke-width: 5
            stroke: blue
        }
    }

    libgreat_git.host_pygreat <-> libgreat-rs_git.firmware: {
        label: usb
        style: {
            font-size: 24
            stroke-width: 5
            stroke: green
        }
    }

    libgreat-rs_git.firmware <-> luna_git.firmware.soc: {
        label: Rust
        style: {
            font-size: 24
            stroke-width: 5
            stroke: orange
        }
    }

    libgreat-rs_git.firmware.platform_drivers <-> luna_git.gateware.soc: {
        label: Rust
        style: {
            font-size: 24
            stroke-width: 5
            stroke: orange
        }
    }

    luna_git.firmware.soc <-> luna_git.gateware: {
        label: Rust
        style: {
            font-size: 24
            stroke-width: 5
            stroke: orange
        }
    }

    luna_git.gateware <-> luna_git.hardware: {
        label: Amaranth
        style: {
            font-size: 24
            stroke-width: 5
            stroke: purple
        }
    }

}





# - Facedancer.git ------------------------------------------------------------

#facedancer: facedancer.git


# - libgreat.git --------------------------------------------------------------

#libgreat: libgreat.git

# libgreat/host/pygreat
#libgreat.pygreat: libgreat/host/pygreat/


# - libgreat-rs.git --------------------------------------------------------------

#libgreat-rs: libgreat-rs.git


# - luna.git ------------------------------------------------------------------

#luna: luna.git

# examples
#luna.examples: luna/examples/
# luna.examples.blinky: luna/examples/blinky/
# luna.examples.soc_bios: luna/examples/soc/bios/
# luna.examples.soc_hello: luna/examples/soc/hello/
# luna.examples.usb: luna/examples/usb/
# luna.examples.usb.loopback: luna/examples/usb/loopback.py
# luna.examples.usb.simple_device: luna/examples/usb/simple_device.py
# luna.examples.usb.stress_test_device: luna/examples/usb/stress_test_device.py

# gateware
#luna.gateware: luna/gateware/
# luna.gateware.applets: luna/gateware/applets/
# luna.gateware.applets.analyzer: luna/gateware/applets/analyzer.py
# luna.gateware.applets.dc_flash: luna/gateware/applets/dc_flash.py
# luna.gateware.architecture_car: luna/gateware/architecture/car.py
# luna.gateware.debug: luna/gateware/debug/
# luna.gateware.interface: luna/gateware/interface/
# luna.gateware.memory.py: luna/gateware/memory.py
# luna.gateware.platform: luna/gateware/platform/
# luna.gateware.soc: luna/gateware/soc/
# luna.gateware.stream: luna/gateware/stream/
# luna.gateware.test: luna/gateware/test/
# luna.gateware.usb: luna/gateware/usb/


# firmware
#luna.firmware: luna/firmware/
