luna_git: luna.git

# - Luna Examples -------------------------------------------------------------

luna_git.examples_soc: examples/soc/
luna_git.examples_soc.text: |c
    bios/
    hello/
|
luna_git.examples_soc: {
    near: luna_git.firmware
}

# - Luna Hardware -------------------------------------------------------------

# luna_git.hardware: hardware/
# luna_git.hardware.usb3343
# luna_git.hardware.w25q32jv

# - Luna Gateware -------------------------------------------------------------

# luna_git.gateware_flash: luna/gateware/interface/flash.py
# luna_git.gateware_flash.ECP5ConfigurationFlashInterface
# luna_git.gateware_usb: luna/gateware/usb/usb2/device.py
# luna_git.gateware_usb.USBDeviceController: USBDeviceController
# luna_git.gateware_flash                   -- luna_git.hardware.w25q32jv
# luna_git.gateware_usb.USBDeviceController -- luna_git.hardware.usb3343

# luna_git.gateware_soc.lunasoc.spiflash -- luna_git.gateware_flash.ECP5ConfigurationFlashInterface
# luna_git.gateware_soc.lunasoc.usb   -- luna_git.gateware_usb.USBDeviceController

# - Luna SoC ------------------------------------------------------------------

luna_git.gateware_soc: luna/gateware/soc/
luna_git.gateware_soc.lunasoc: luna/gateware/soc/lunasoc.py
luna_git.gateware_soc.lunasoc: {
    cpu: minerva
    bus_arbiter: bus arbiter
    bus_decoder: bus decoder
    intc: interrupt controller

    gpio
    hyperram
    jtag
    pmod: pmod0, pmod1
    spiflash
    sram
    timer
    uart
    usb: usb0, usb1, usb2

    cpu -- jtag
    cpu -- bus_arbiter
    bus_arbiter -- bus_decoder
    bus_decoder -- intc
    intc -- cpu
    uart -- intc
    timer -- intc

    bus_decoder -- gpio
    bus_decoder -- hyperram
    bus_decoder -- spiflash
    bus_decoder -- sram
    bus_decoder -- timer
    bus_decoder -- uart
    bus_decoder -- usb

    gpio -- pmod
}

luna_git.gateware_soc.lunasoc.cpu.style: { fill: lightblue }
luna_git.gateware_soc.lunasoc.bus_arbiter.style: { fill: lightgreen }
luna_git.gateware_soc.lunasoc.bus_decoder.style: { fill: lightgreen }
luna_git.gateware_soc.lunasoc.intc.style: { fill: lightgreen }

luna_git.gateware_soc.lunasoc.gpio.style.fill: orange
luna_git.gateware_soc.lunasoc.hyperram.style.fill: orange
luna_git.gateware_soc.lunasoc.spiflash.style.fill: orange
luna_git.gateware_soc.lunasoc.sram.style.fill: orange
luna_git.gateware_soc.lunasoc.timer.style.fill: orange
luna_git.gateware_soc.lunasoc.uart.style.fill: orange
luna_git.gateware_soc.lunasoc.usb.style.fill: orange



luna_git.gateware_soc.cgen: luna/gateware/soc/cgen.py
luna_git.gateware_soc.cgen.text: |c
    resources.h
    soc.ld
|

luna_git.gateware_soc.svdgen: luna/gateware/soc/svdgen.py
luna_git.gateware_soc.svdgen.text: |c
    lunasoc.svd
|

luna_git.gateware_soc.lunasoc -> luna_git.gateware_soc.cgen
luna_git.gateware_soc.lunasoc -> luna_git.gateware_soc.svdgen

luna_git.gateware_soc.cgen -- luna_git.examples_soc
luna_git.gateware_soc.svdgen -- luna_git.firmware.lunasoc-pac: svd2rust


# - Luna Firmware -------------------------------------------------------------

luna_git.firmware: firmware/soc/

luna_git.firmware.lunasoc-pac: firmware/soc/lunasoc-pac/
luna_git.firmware.lunasoc-pac.text: |c
    build.rs
    device.x
    lib.rs
|

luna_git.firmware.lunasoc-hal: firmware/soc/lunasoc-hal/
luna_git.firmware.lunasoc-hal.text: |c
    flash.rs  (libgreat-rs.ECP5ConfigurationFlashInterface)
    gpio.rs   (libgreat-rs.GpioPeripehral)
    serial.rs (libgreat-rs.AsyncSerial)
    timer.rs  (libgreat-rs.TimerPeripheral)
    usb_hs.rs (libgreat-rs.USBDeviceController)
|

luna_git.firmware.luna-usb: firmware/soc/luna-usb/
luna_git.firmware.luna-usb.text: |c
    service_heartbeat
    task_usb_streaming
|

luna_git.firmware.lunasoc-pac -- luna_git.firmware.lunasoc-hal
luna_git.firmware.lunasoc-pac -- luna_git.firmware.luna-usb
luna_git.firmware.lunasoc-hal -- luna_git.firmware.luna-usb

luna_git.firmware.lunasoc-hal -- libgreat-rs_git


embedded-hal_git: @rust-embedded/embedded-hal.git {
    near: luna_git.firmware.lunasoc-hal
}
embedded-hal_git.text: |c
    delay
    digital
    serial
    spi
    timer
    watchdog
    ...
|

luna_git.firmware.lunasoc-hal -- embedded-hal_git

# - libgreat-rs ---------------------------------------------------------------

libgreat-rs_git: libgreat-rs.git

libgreat-rs_git.firmware_classes: firmware/classes/
libgreat-rs_git.firmware_classes.text: |c
    core.rs
    firmware.rs
|

libgreat-rs_git.firmware_drivers: firmware/drivers/
libgreat-rs_git.firmware_drivers.text: |c
    comms/comms_class.rs
    error.rs
    memory/allocator.rs
    reset.rs
|

libgreat-rs_git.firmware_platform_drivers: firmware/platform/soc/drivers/
libgreat-rs_git.firmware_platform_drivers.text: |c
    amaranth_stdio.serial.AsyncSerial.rs
    lambdasoc.periph.Peripheral -> GpioPeripheral.rs
    lambdasoc.periph.timer.TimerPeripheral.rs
    luna.gateware.interface.flash.ECP5ConfigurationFlashInterface.rs
    luna.gateware.usb2.USBDeviceController.rs
|
