[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
#riscv = "=0.9.0"

[profile.release]
opt-level = "s"
debug-assertions = false
overflow-checks = false
codegen-units = 1
incremental = false
debug = true
lto = true
